language: python
python: "3.6"

install:
- pip install requests
- pip install pyre-check
- pip install pytest-cov

script:
- python3 -m pytest --cov-report term-missing --cov=changelog_generator
- pyre init .
- pyre --source-directory . check